<<<<<<< HEAD
# Generated by Django 4.0.7 on 2022-08-18 00:08
=======
# Generated by Django 4.0.7 on 2022-08-18 17:36
>>>>>>> 7e189fe287b0866d516afdceff4ac808f1e5e7fe

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_accounts_id',
            field=models.PositiveIntegerField(default=0, verbose_name='프로바이더 회원번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_type_code',
            field=models.CharField(choices=[('local', '로컬'), ('kakao', '카카오')], default='local', max_length=20, verbose_name='프로바이더 타입코드'),
        ),
    ]
