# Generated by Django 4.0.7 on 2022-08-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(
                    default=None, null=True, verbose_name='삭제일')),
                ('status', models.PositiveIntegerField(
                    default=0, verbose_name='상태코드')),
                ('reg_date', models.DateTimeField(
                    auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(
                    auto_now=True, null=True, verbose_name='수정날짜')),
                ('context', models.CharField(max_length=50, verbose_name='할일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(
                    default=None, null=True, verbose_name='삭제일')),
                ('status', models.PositiveIntegerField(
                    default=0, verbose_name='상태코드')),
                ('reg_date', models.DateTimeField(
                    auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(
                    auto_now=True, null=True, verbose_name='수정날짜')),
                ('name', models.CharField(max_length=50, verbose_name='블로그이름')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
