# Generated by Django 4.0.5 on 2022-07-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_status_comment_status_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(verbose_name='버켓오브젝트ID')),
                ('dataURL', models.TextField(verbose_name='경로')),
                ('size', models.JSONField(verbose_name='가로세로길이')),
                ('type', models.CharField(max_length=20, verbose_name='파일타입')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blog.article')),
            ],
        ),
    ]
