# Generated by Django 4.0.5 on 2022-06-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='test', max_length=50, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
